# Generated by Django 4.2.8 on 2023-12-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontos_turisticos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
