# Generated by Django 4.2.8 on 2023-12-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontos_turisticos_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='Avaliacao',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
    ]
