# Generated by Django 4.2.8 on 2023-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('core', '0005_pontos_turisticos_avaliacao'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='pontos_turisticos',
            name='endereco',
            field=models.ManyToManyField(to='localizacao.endereco'),
        ),
    ]
