# Generated by Django 4.2.8 on 2023-12-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0006_rename_avaliacao_pontos_turisticos_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontos_turisticos',
            name='Avaliacao',
        ),
        migrations.AddField(
            model_name='pontos_turisticos',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
    ]
